package br.jus.trf1.core.enums;

public enum OcupacaoProfissionalEnum {
    MEMBRO_PODER_EXECUTIVO("101", "Membro do Poder Executivo"),
    MEMBRO_PODER_JUDICIARIO("102", "Membro do Poder Judiciário e de Tribunal de Contas"),
    MEMBRO_PODER_LEGISLATIVO("103", "Membro do Poder Legislativo"),
    MEMBRO_MINISTERIO_PUBLICO("104", "Membro do Ministério Público"),
    DIRIGENTE_SUPERIOR_ADMINISTRACAO_PUBLICA("105", "Dirigente superior da administração pública"),
    DIPLOMATA("106", "Diplomata e afins"),
    SERVIDOR_CARREIRAS_PODER_LEGISLATIVO("107", "Servidor das carreiras do Poder Legislativo"),
    SERVIDOR_CARREIRAS_MINISTERIO_PUBLICO("108", "Servidor das carreiras do Ministério Público"),
    SERVIDOR_CARREIRAS_PODER_JUDICIARIO("109", "Servidor das carreiras do Poder Judiciário"),
    ADVOGADO_SETOR_PUBLICO("110", "Advogado do setor público"),
    SERVIDOR_CARREIRAS_AUDITORIA_FISCAL("111", "Servidor das carreiras de auditoria fiscal"),
    SERVIDOR_CARREIRAS_BANCO_CENTRAL("112", "Servidor das carreiras do Banco Central, CVM e Susep"),
    DELEGADO_POLICIA("113", "Delegado de Polícia e outros servidores das carreiras de polícia"),
    SERVIDOR_CARREIRAS_GESTAO_GOVERNAMENTAL("114", "Servidor das carreiras de gestão governamental"),
    SERVIDOR_CARREIRAS_CIENCIA_TECNOLOGIA("115", "Servidor das carreiras de ciência e tecnologia"),
    SERVIDOR_OUTRAS_CARREIRAS_ADMINISTRACAO_PUBLICA("116", "Servidor das demais carreiras da administração pública"),
    TITULAR_CARTORIO("117", "Titular de Cartório"),
    DIRIGENTE_PARTIDO_POLITICO("118", "Dirigente ou administrador de partido político"),
    DIRIGENTE_EMPRESA_INDUSTRIAL("120", "Dirigente, presidente e diretor de empresa industrial"),
    PRESIDENTE_DIRETOR_EMPRESA_PUBLICA("121", "Presidente e diretor de empresa pública e sociedade de economia mista"),
    GERENTE_SUPERVISOR_EMPRESA_INDUSTRIAL("130", "Gerente ou supervisor de empresa industrial"),
    GERENTE_SUPERVISOR_EMPRESA_PUBLICA("131", "Gerente ou supervisor de empresa pública e sociedade de economia mista"),
    PRESIDENTE_DIRETOR_ORGANISMO_INTERNACIONAL("140", "Presidente, diretor, gerente e supervisor de organismo internacional"),
    MATEMATICO_ESTATISTICO("211", "Matemático, estatístico, atuário e afins"),
    ANALISTA_SISTEMAS_DESENVOLVEDOR("212", "Analista de sistemas, desenvolvedor de software, administrador de redes"),
    FISICO_QUIMICO("213", "Físico, químico, meteorologista, geólogo, oceanógrafo e afins"),
    ENGENHEIRO_ARQUITETO("214", "Engenheiro, arquiteto e afins"),
    PILOTO_AERONAVES("215", "Piloto de aeronaves, comandante de embarcações e oficiais de máquinas"),
    BIOLOGO_AGRONOMO("221", "Biólogo, biomédico e afins"),
    AGRONOMO("222", "Agrônomo e afins"),
    PROFISSIONAL_EDUCACAO_FISICA("224", "Profissional da educação física"),
    MEDICO("225", "Médico"),
    ODONTOLOGO("226", "Odontólogo"),
    ENFERMEIRO_NUTRICIONISTA("227", "Enfermeiro de nível superior, nutricionista, farmacêutico e afins"),
    VETERINARIO("228", "Veterinário, patologista (veterinário) e zootecnista"),
    FONOAUDIOLOGO_FISIOTERAPEUTA("229", "Fonoaudiólogo, fisioterapeuta, terapeuta ocupacional e afins"),
    ADVOGADO("241", "Advogado"),
    SOCIOLOGO_CIENTISTA_POLITICO("250", "Sociólogo e cientista político"),
    ANTROPOLOGO_ARQUEOLOGO("251", "Antropólogo e arqueólogo"),
    ECONOMISTA_ADMINISTRADOR("252", "Economista, administrador, contador, auditor e afins"),
    PROFISSIONAL_MARKETING("253", "Profissional de marketing, de publicidade e de comercialização"),
    PSICANALISTA("254", "Psicanalista"),
    PSICOLOGO("255", "Psicólogo"),
    GEOGRAFO("256", "Geógrafo"),
    HISTORIADOR("257", "Historiador"),
    ASSISTENTE_SOCIAL("258", "Assistente social e economista doméstico"),
    FILOSOFO("259", "Filósofo"),
    JORNALISTA_REPORTER("261", "Jornalista e repórter"),
    SACERDOTE_MEMBRO_ORDENS_RELIGIOSAS("263", "Sacerdote ou membro de ordens ou seitas religiosas"),
    TRADUTOR_INTERPRETE_FILOLOGO("264", "Tradutor, intérprete, filólogo"),
    BIBLIOTECARIO_DOCUMENTALISTA("265", "Bibliotecário, documentalista, arquivólogo, museólogo"),
    ESCRITOR_REDATOR("266", "Escritor, crítico, redator"),
    CENOGRAGO_DECORADOR("276", "Cenógrafo, decorador de interiores"),
    EMPRESARIO_PRODUTOR_ESPETACULOS("277", "Empresário e produtor de espetáculos"),
    OUTROS_PROFISSIONAIS_ESPETACULO_ARTES("279", "Outros profissionais do espetáculo e das artes"),
    PROFESSOR_EDUCACAO_INFANTIL("290", "Professor na educação infantil"),
    PROFESSOR_ENSINO_FUNDAMENTAL("291", "Professor do ensino fundamental"),
    PROFESSOR_ENSINO_MEDIO("292", "Professor do ensino médio"),
    PROFESSOR_ENSINO_PROFISSIONAL("293", "Professor do ensino profissional"),
    PROFESSOR_ENSINO_SUPERIOR("294", "Professor do ensino superior"),
    INSTRUTOR_PROFESSOR_ESCOLAS_LIVRES("295", "Instrutor e professor de escolas livres"),
    PEDAGOGO_ORIENTADOR_EDUCACIONAL("296", "Pedagogo, orientador educacional"),
    TECNICO_CIENCIAS_FISICAS_QUIMICAS("311", "Técnico em ciências físicas e químicas"),
    TECNICO_CONSTRUCAO_CIVIL_EDIFICACOES("312", "Técnico em construção civil, de edificações e obras de infraestrutura"),
    TECNICO_ELETRO_ELETRONICA_FOTONICA("313", "Técnico em eletro-eletrônica e fotônica"),
    TECNICO_METALMECANICA("314", "Técnico em metalmecânica"),
    TECNICO_MINERALOGIA_GEOLOGIA("316", "Técnico em mineralogia e geologia"),
    TECNICO_INFORMATICA("317", "Técnico em informática"),
    DESENHISTA_TECNICO_MODELISTA("318", "Desenhista técnico e modelista"),
    OUTROS_TECNICOS_NIVEL_MEDIO_CIENCIAS("319", "Outros técnicos de nível médio das ciências físicas, químicas, engenharia e afins"),
    TECNICO_BIOLOGIA("320", "Técnico em biologia"),
    TECNICO_PRODUCAO_AGROPECUARIA("321", "Técnico da produção agropecuária"),
    TECNICO_CIENCIA_SAUDE_HUMANA("322", "Técnico da ciência da saúde humana"),
    TECNICO_CIENCIA_SAUDE_ANIMAL("323", "Técnico da ciência da saúde animal"),
    TECNICO_LABORATORIO_RAIO_X("324", "Técnico de laboratório, Raios-X e outros equipamentos e instrumentos de diagnóstico"),
    TECNICO_BIOQUIMICA_BIOTECNOLOGIA("325", "Técnico de bioquímica e da biotecnologia"),
    TECNICO_CONSERVACAO_DISSECACAO_EMPALHAMENTO("328", "Técnico de conservação, dissecação e empalhamento de corpos"),
    TECNICO_CIENCIAS_ADMINISTRATIVAS_CONTABEIS("351", "Técnico das ciências administrativas e contábeis"),
    TECNICO_INSPECAO_FISCALIZACAO_COORDENACAO_ADMINISTRATIVA("352", "Técnico de inspeção, fiscalização e coordenação administrativa"),
    AGENTE_BOLSA_VALORES_CAMBIO_SERVICOS_FINANCEIROS("353", "Agente de Bolsa de Valores, câmbio e outros serviços financeiros"),
    AGENTE_REPRESENTANTE_COMERCIAL_CORRETOR("354", "Agente e representante comercial, corretor, leiloeiro e afins"),
    CORRETOR_ADMINISTRADOR_IMOVEIS("355", "Corretor e Administrador de Imóveis"),
    TECNICO_SERVICOS_CULTURAIS("371", "Técnico de serviços culturais"),
    CINEGRAFISTA_FOTOGRAFO_TECNICOS_MAQUINAS_TRATAMENTO_DADOS("372", "Cinegrafista, fotógrafo e outros técnicos em operação de máquinas de tratamento de dados"),
    TECNICO_OPERACAO_ESTACOES_RADIO_TELEVISAO("373", "Técnico em operação de estações de rádio e televisão"),
    TECNICO_OPERACAO_APARELHOS_SONORIZACAO_CENOGRAGIA_PROJECAO("374", "Técnico em operação de aparelhos de sonorização, cenografia e projeção"),
    DECORADOR_VITRINISTA("375", "Decorador e vitrinista"),
    APRESENTADOR_ARTISTAS_POPULARES_MODELOS("376", "Apresentador, artistas de artes populares e modelos"),
    ATLETA_DESPORTISTA("377", "Atleta, desportista e afins"),
    OUTROS_TECNICOS_NIVEL_MEDIO("391", "Outros técnicos de nível médio"),
    BANCARIO_ECONOMIARIO_ESCRITURARIO_SECRETARIO_ASSISTENTE_AUXILIAR_ADMINISTRATIVO("410", "Bancário, economiário, escriturário, secretário, assistente e auxiliar administrativo"),
    TRABALHADOR_ATENDIMENTO_PUBLICO_CAIXA_DESPACHANTE_RECENSEADOR("420", "Trabalhador de atendimento ao público, caixa, despachante, recenseador e afins"),
    COMISSARIO_BORDO_GUIA_TURISMO_AGENTE_VIAGEM("511", "Comissário de bordo, guia de turismo, agente de viagem e afins"),
    TRABALHADOR_SERVICOS_DOMESTICOS_EM_GERAL("512", "Trabalhador dos serviços domésticos em geral"),
    TRABALHADOR_SERVICOS_HOTELARIA_ALIMENTACAO("513", "Trabalhador dos serviços de hotelaria e alimentação"),
    TRABALHADOR_SERVICOS_ADMINISTRACAO_CONSERVACAO_MANUTENCAO_EDIFICIOS("514", "Trabalhador dos serviços de administração, conservação e manutenção de edifícios"),
    TRABALHADOR_SERVICOS_SAUDE("515", "Trabalhador dos serviços de saúde"),
    TRABALHADOR_SERVICOS_EMBELEZAMENTO_CUIDADOS_PESSOAIS("516", "Trabalhador dos serviços de embelezamento e cuidados pessoais"),
    TRABALHADOR_SERVICOS_PROTECAO_SEGURANCA("517", "Trabalhador dos serviços de proteção e segurança"),
    MOTORISTA_CONDUTOR_TRANSPORTE_PASSAGEIROS("518", "Motorista e condutor do transporte de passageiros"),
    OUTROS_TRABALHADORES_SERVICOS_DIVERSOS("519", "Outros trabalhadores de serviços diversos"),
    CAMELO_VENDEDOR_PRESTADOR_SERVICOS_COMERCIO("529", "Vendedor e prestador de serviços do comércio, ambulante, caixeiro-viajante e camelô"),
    PRODUTOR_EXPLORACAO_AGROPECUARIA("610", "Produtor na exploração agropecuária"),
    TRABALHADOR_EXPLORACAO_AGROPECUARIA("620", "Trabalhador na exploração agropecuária"),
    PESCADOR_CACADOR_EXTRATIVISTA_FLORESTAL("630", "Pescador, caçador e extrativista florestal"),
    OPERADOR_MAQUINA_AGROPECUARIA_FLORESTAL("640", "Operador de máquina agropecuária e florestal"),
    TRABALHADOR_INDUSTRIA_EXTRATIVA_CONSTRUCAO_CIVIL("710", "Trabalhador da indústria extrativa e da construção civil"),
    TRABALHADOR_TRANSFORMACAO_METAIS_COMPOSITOS("720", "Trabalhador da transformação de metais e compósitos"),
    TRABALHADOR_FABRICACAO_INSTALACAO_ELETRO_ELETRONICA("730", "Trabalhador da fabricação e instalação eletro-eletrônica"),
    MONTADOR_APARELHOS_INSTRUMENTOS_PRECISAO_MUSICOS("740", "Montador de aparelhos e instrumentos de precisão e musicais"),
    JOALHEIRO_VIDREIRO_CERAMISTA("750", "Joalheiro, vidreiro, ceramista e afins"),
    TRABALHADOR_INDUSTRIAS_TEXTIL_CURTIMENTO_VESTUARIO_ARTES_GRAFICAS("760", "Trabalhador das indústrias têxteis, do curtimento, do vestuário e das artes gráficas"),
    TRABALHADOR_INDUSTRIAS_MADEIRA_MOBILIARIO("770", "Trabalhador das indústrias de madeira e do mobiliário"),
    CONDUTOR_OPERADOR_ROBOS_VEICULOS_EQUIPAMENTOS_MOVIMENTACAO_CARGA("780", "Condutor e operador de robôs, veículos de equipamentos de movimentação de carga e afins"),
    TRABALHADOR_INDUSTRIAS_QUIMICA_PETROQUIMICA_BORRACHA_PLASTICO("810", "Trabalhador das indústrias química, petroquímica, borracha e plástico e afins"),
    TRABALHADOR_INSTALACOES_SIDERURGICAS_MATERIAIS_CONSTRUCAO("820", "Trabalhador de instalações siderúrgicas e de materiais de construção"),
    TRABALHADOR_INSTALACOES_MAQUINAS_FABRICACAO_CELULOSE_PAPEL("830", "Trabalhador de instalações e máquinas de fabricação de celulose e papel"),
    TRABALHADOR_FABRICACAO_ALIMENTOS_BEBIDAS_FUMO_AGROINDUSTRIAS("840", "Trabalhador da fabricação de alimentos, bebidas, fumo e de agroindústrias"),
    OPERADOR_INSTALACOES_PRODUCAO_DISTRIBUICAO_ENERGIA("860", "Operador de instalações de produção e distribuição de energia"),
    TRABALHADOR_OUTRAS_INSTALACOES_AGROINDUSTRIAIS("870", "Trabalhador de outras instalações agroindustriais"),
    TRABALHADOR_REPARACAO_MANUTENCAO("900", "Trabalhador de reparação e manutenção"),
    MILITAR_AERONAUTICA("10", "Militar da Aeronáutica"),
    MILITAR_EXERCITO("20", "Militar do Exército"),
    MILITAR_MARINHA("30", "Militar da Marinha"),
    POLICIAL_MILITAR("40", "Policial Militar"),
    BOMBEIRO_MILITAR("50", "Bombeiro Militar"),
    SEM_OCUPACOES("0", "Sem ocupações");

    private String codigo;
    private String descricao;

    OcupacaoProfissionalEnum(String codigo, String descricao) {
        this.codigo = codigo;
        this.descricao = descricao;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
}
