package br.jus.trf1.core.enums;

/**
 * Define a lista de órgãos emissores federais
 *
 * @author bruno.carneiro (tr301605)
 */
public enum OrgaoEmissorEnum {
    ABNC("ABNC", "Academia Brasileira de Neurocirurgia"),
    AGU("AGU", "Advocacia-Geral da União"),
    ANAC("ANAC", "Agência Nacional de Aviação Civil"),
    CAER("CAER", "Clube de Aeronáutica"),
    CAU("CAU", "Conselho de Arquitetura e Urbanismo"),
    CBM("CBM", "Corpo de Bombeiro Militar"),
    CFA("CFA", "Conselho Federal Administração"),
    CFB("CFB", "Conselho Federal de Biblioteconomia"),
    CFBIO("CFBIO", "Conselho Federal de Biologia"),
    CFBM("CFBM", "Conselho Federal de Biomedicina"),
    CFC("CFC", "Conselho Federal de Contabilidade"),
    CFESS("CFESS", "Conselho Federal de Serviço Social"),
    CFF("CFF", "Conselho Regional de Farmácia"),
    CFFA("CFFA", "Conselho Federal de Fonoaudiologia"),
    CFM("CFM", "Conselho Federal de Medicina"),
    CFMV("CFMV", "Conselho Federal de Medicina Veterinária"),
    CFN("CFN", "Conselho Federal de Nutrição"),
    CFO("CFO", "Conselho Federal de Odontologia"),
    CFP("CFP", "Conselho Federal de Psicologia"),
    CFQ("CFQ", "Conselho Regional de Química"),
    CFT("CFT", "Conselho Federal dos Técnicos Industriais"),
    CFTA("CFTA", "Conselho Federal dos Técnicos Agrícolas"),
    CGPI("CGPI", "Coordenação Geral de Privilégios e Imunidades"),
    CGPMAF("CGPMAF", "Coordenadoria Geral de Polícia Marítima, Aeronáutica e de Fronteiras"),
    CIPC("CIPC", "Centro de Inteligência da Polícia Civil"),
    CNIG("CNIG", "Conselho Nacional de Imigração"),
    CNT("CNT", "Confederação Nacional do Transporte"),
    CNTV("CNTV", "Confederação Nacional de Vigilantes & Prestadores de Serviços"),
    COFECI("COFECI", "Conselho Federal de Corretores de Imóveis"),
    COFECON("COFECON", "Conselho Federal de Economia"),
    COFEM("COFEM", "Conselho Federal de Museologia"),
    COFEN("COFEN", "Conselho Federal de Enfermagem"),
    COFFITO("COFFITO", "Conselho Regional de Fisioterapia e Terapia Ocupacional"),
    COMAER("COMAER", "Comando da Aeronáutica"),
    CONFE("CONFE", "Conselho Federal de Estatística"),
    CONFEA("CONFEA", "Conselho Federal de Engenharia e Agronomia"),
    CONFEF("CONFEF", "Conselho Federal de Educação Física"),
    CONFERE("CONFERE", "Conselho Federal dos Representantes Comerciais"),
    CONRE("CONRE", "Conselho Regional de Estatística"),
    CONRERP("CONRERP", "Conselho Federal de Profissionais de Relações Públicas"),
    CORE("CORE", "Conselho Regional dos Representantes Comerciais"),
    CORECON("CORECON", "Conselho Regional de Economia"),
    COREM("COREM", "Conselho Regional de Museologia"),
    COREN("COREN", "Conselho Regional de Enfermagem"),
    CRA("CRA", "Conselho Regional de Administração"),
    CRAS("CRAS", "Centro de Referência de Assistência Social"),
    CRB("CRB", "Conselho Regional de Biblioteconomia"),
    CRBIO("CRBIO", "Conselho Regional de Biologia"),
    CRBM("CRBM", "Conselho Regional de Biomedicina"),
    CRC("CRC", "Conselho Regional de Contabilidade"),
    CREA("CREA", "Conselho Regional de Engenharia e Agronomia"),
    CRECI("CRECI", "Conselho Regional de Corretores de Imóveis"),
    CREF("CREF", "Conselho Regional de Educação Física"),
    CREFITO("CREFITO", "Conselho Regional de Fisioterapia e Terapia Ocupacional"),
    CRESS("CRESS", "Conselho Regional de Serviço Social"),
    CRF("CRF", "Conselho Regional de Farmácia"),
    CRFA("CRFA", "Conselho Regional de Fonoaudiologia"),
    CRM("CRM", "Conselho Regional de Medicina"),
    CRMV("CRMV", "Conselho Regional de Medicina Veterinária"),
    CRN("CRN", "Conselho Regional de Nutrição"),
    CRO("CRO", "Conselho Regional de Odontologia"),
    CRP("CRP", "Conselho Regional de Psicologia"),
    CRPRE("CRPRE", "Conselho Regional de Profissionais de Relações Públicas"),
    CRQ("CRQ", "Conselho Regional de Química"),
    CRT("CRT", "Conselho Regional dos Técnicos Industriais"),
    CRTA("CRTA", "Conselho Regional de Técnicos de Administração"),
    CTPS("CTPS", "Carteira de Trabalho e Previdência Social"),
    CV("CV", "Cartório Civil"),
    DELEMIG("DELEMIG", "Delegacia de Polícia de Imigração"),
    DETRAN("DETRAN", "Departamento Estadual de Trânsito"),
    DGPC("DGPC", "Diretoria Geral da Polícia Civil"),
    DIC("DIC", "Diretoria de Identificação Civil"),
    DICC("DICC", "Diretoria de Identificação Civil e Criminal"),
    DIREX("DIREX", "Diretoria Executiva"),
    DPF("DPF", "Departamento de Polícia Federal"),
    DPMAF("DPMAF", "Divisão de Polícia Marítima, Aérea e de Fronteiras"),
    DPT("DPT", "Departamento de Polícia Técnica Geral"),
    DPTC("DPTC", "Departamento de Polícia Técnico Científica"),
    DREX("DREX", "Delegacia Regional Executiva"),
    DRT("DRT", "Delegacia Regional do Trabalho"),
    EB("EB", "Exército Brasileiro"),
    FAB("FAB", "Força Aérea Brasileira"),
    FENAJ("FENAJ", "Federação Nacional dos Jornalistas"),
    FGTS("FGTS", "Fundo de Garantia do Tempo de Serviço"),
    FIPE("FIPE", "Fundação Instituto de Pesquisas Econômicas"),
    FLS("FLS", "Fundação Lyndolpho Silva"),
    FUNAI("FUNAI", "Fundação Nacional do Índio"),
    GEJSP("GEJSP", "Gerência de Estado de Justiça, Segurança Pública e Cidadania"),
    GEJSPC("GEJSPC", "Gerência de Estado de Justiça, Segurança Pública e Cidadania"),
    GEJUSPC("GEJUSPC", "Gerência de Estado de Justiça, Segurança Pública e Cidadania"),
    GESP("GESP", "Gerência de Estado de Segurança Pública"),
    GOVGO("GOVGO", "Governo do Estado de Goiás"),
    I_CLA("I_CLA", "Carteira de Identidade Classista"),
    ICP("ICP", "Instituto de Polícia Científica"),
    IDAMP("IDAMP", "Instituto de Identificação Dr. Aroldo Mendes Paiva"),
    IFP("IFP", "Instituto Félix Pacheco"),
    IGP("IGP", "Instituto Geral de Perícias"),
    IIACM("IIACM", "Instituto de Identificação Aderson Conceição de Melo"),
    IICC("IICC", "Instituto de Identificação Civil e Criminal"),
    IICCECF("IICCECF", "Instituto de Identificação Civil e Criminal Engrácia da Costa Francisco"),
    IICM("IICM", "Instituto de Identificação Carlos Menezes"),
    IIGP("IIGP", "Instituto de Identificação Gonçalo Pereira"),
    IIJDM("IIJDM", "Instituto de Identificação João de Deus Martins"),
    IIPC("IIPC", "Instituto de Identificação da Polícia Civil"),
    IIPM("IIPC", "Instituto de Identificação Pedro Mello"),
    IIRGD("IIRGD", "Instituto de Identificação Ricardo Gumbleton Daunt"),
    IIRHM("IIRHM", "Instituto de Identificação Raimundo Hermínio de Melo"),
    IITB("IITB", "Instituto de Identificação Tavares Buril"),
    IML("IML", "Instituto Médico-Legal"),
    INI("INI", "Instituto Nacional de Identificação"),
    IPF("IPF", "Instituto Pereira Faustino"),
    ITCP("ITCP", "Instituto Técnico-Científico de Perícia"),
    ITEP("ITEP", "Instituto Técnico-Científico de Perícia"),
    MAER("MAER", "Ministério da Aeronáutica"),
    MB("MB", "Marinha do Brasil"),
    MD("MD", "Ministério da Defesa"),
    MDS("MDS", "Ministério da Cidadania"),
    MEC("MEC", "Ministério da Educação e Cultura"),
    MEX("MEX", "Ministério do Exército"),
    MINDEF("MINDEF", "Ministério da Defesa"),
    MJ("MJ", "Ministério da Justiça"),
    MM("MM", "Ministério da Marinha"),
    MMA("MMA", "Ministério da Marinha"),
    MPAS("MPAS", "Ministério da Previdência e Assistência Social"),
    MPE("MPE", "Ministério Público Estadual"),
    MPF("MPF", "Ministério Público Federal"),
    MPT("MPT", "Ministério Público do Trabalho"),
    MRE("MRE", "Ministério das Relações Exteriores"),
    MT("MT", "Ministério do Trabalho"),
    MTE("MTE", "Ministério da Economia"),
    MTPS("MTPS", "Ministério do Trabalho e Previdência Social"),
    NUMIG("NUMIG", "Núcleo de Polícia de Imigração"),
    OAB("OAB", "Ordem dos Advogados do Brasil"),
    OMB("OMB", "Ordens dos Músicos do Brasil"),
    PC("PC", "Polícia Civil"),
    PF("PF", "Polícia Federal"),
    PGFN("PGFN", "Procuradoria Geral da Fazenda Nacional"),
    PM("PM", "Polícia Militar"),
    POLITEC("POLITEC", "Perícia Oficial e Identificação Técnica"),
    PRF("PRF", "Polícia Rodoviária Federal"),
    PTC("PTC", "Polícia Tecnico-Científica"),
    SCC("SCC", "Secretaria de Estado da Casa Civil"),
    SCJDS("SCJDS", "Secretaria Coordenadora de Justiça e Defesa Social"),
    SDS("SDS", "Secretaria de Defesa Social"),
    SECC("SECC", "Secretaria de Estado da Casa Civil"),
    SECCDE("SECCDE", "Secretaria de Estado da Casa Civil e Desenvolvimento Econômico"),
    SEDS("SEDS", "Secretaria de Estado da Defesa Social"),
    SEGUP("SEGUP", "Secretaria de Estado da Segurança Pública e da Defesa Social"),
    SEJSP("SEJSP", "Secretaria de Estado de Justiça e Segurança Pública"),
    SEJUC("SEJUC", "Secretaria de Estado da Justica"),
    SEJUSP("SEJUSP", "Secretaria de Estado de Justiça e Segurança Pública"),
    SEPC("SEPC", "Secretaria de Estado da Polícia Civil"),
    SES("SES", "Secretaria de Estado da Segurança"),
    SESC("SESC", "Secretaria de Estado da Segurança e Cidadania"),
    SESDC("SESDC", "Secretaria de Estado da Segurança, Defesa e Cidadania"),
    SESDEC("SESDEC", "Secretaria de Estado da Segurança, Defesa e Cidadania"),
    SESEG("SESEG", "Secretaria Estadual de Segurança"),
    SESP("SESP", "Secretaria de Estado da Segurança Pública"),
    SESPAP("SESPAP", "Secretaria de Estado da Segurança Pública e Administração Penitenciária"),
    SESPDC("SESPDC", "Secretaria de Estado de Segurança Publica e Defesa do Cidadão"),
    SESPDS("SESPDS", "Secretaria de Estado de Segurança Pública e Defesa Social"),
    SGPC("SGPC", "Superintendência Geral de Polícia Civil"),
    SGPJ("SGPJ", "Superintendência Geral de Polícia Judiciária"),
    SIM("SIM", "Serviço de Identificação da Marinha"),
    SJ("SJ", "Secretaria da Justiça"),
    SJCDH("SJCDH", "Secretaria da Justiça e dos Direitos Humanos"),
    SJDS("SJDS", "Secretaria Coordenadora de Justiça e Defesa Social"),
    SJS("SJS", "Secretaria da Justiça e Segurança"),
    SJTC("SJTC", "Secretaria da Justiça do Trabalho e Cidadania"),
    SJTS("SJTS", "Secretaria da Justiça do Trabalho e Segurança"),
    SNJ("SNJ", "Secretaria Nacional de Justiça / Departamento de Estrangeiros"),
    SPMAF("SPMAF", "Serviço de Polícia Marítima, Aérea e de Fronteiras"),
    SPTC("SPTC", "Secretaria de Polícia Técnico-Científica"),
    SRDPF("SRDPF", "Superintendência Regional do Departamento de Polícia Federal"),
    SRF("SRF", "Receita Federal"),
    SRTE("SRTE", "Superintendência Regional do Trabalho"),
    SSDC("SSDC", "Secretaria da Segurança, Defesa e Cidadania"),
    SSDS("SSDS", "Secretaria da Segurança e da Defesa Social"),
    SSI("SSI", "Secretaria de Segurança e Informações"),
    SSP("SSP", "Secretaria de Segurança Pública"),
    SSPCGP("SSPCGP", "Secretaria de Segurança Pública e Coordenadoria Geral de Perícias"),
    SSPDC("SSPDC", "Secretaria de Segurança Pública e Defesa do Cidadão"),
    SSPDS("SSPDS", "Secretaria de Segurança Pública e Defesa Social"),
    SSPPC("SSPPC", "Secretaria de Segurança Pública Polícia Civil"),
    SUSEP("SUSEP", "Superintendência de Seguros Privados"),
    SUSEPE("SUSEPE", "Superintendência dos Serviços Penitenciários"),
    TJ("TJ", "Tribunal de Justiça"),
    TJAEM("TJAEM", "Tribunal Arbitral e Mediação dos Estados Brasileiros"),
    TRE("TRE", "Tribunal Regional Eleitoral"),
    TRF("TRF", "Tribunal Regional Federal"),
    TSE("TSE", "Tribunal Superior Eleitoral"),
    XXX("XXX", "Orgão Estrangeiro"),
    ZZZ("ZZZ", "Outro");

    private final String sigla;
    private final String nome;

    OrgaoEmissorEnum(String sigla, String nome) {
        this.sigla = sigla;
        this.nome = nome;
    }

    public String getSigla() {
        return sigla;
    }

    public String getNome() {
        return nome;
    }
}
