package br.jus.trf1.core.enums;

public enum OrigensTRF1Enum {
    SUBSECAO_JUDICIARIA_DE_ANAPOLIS("SUBSEÇÃO JUDICIÁRIA DE ANÁPOLIS", "ANS", UnidadeFederativaEnum.GO, "3502"),
    SUBSECAO_JUDICIARIA_DE_RIO_VERDE("SUBSEÇÃO JUDICIÁRIA DE RIO VERDE", "RVD", UnidadeFederativaEnum.GO, "3503"),
    SUBSECAO_JUDICIARIA_DE_APARECIDA_DE_GOIANIA("SUBSEÇÃO JUDICIÁRIA DE APARECIDA DE GOIÂNIA", "ACG", UnidadeFederativaEnum.GO, "3504"),
    SUBSECAO_JUDICIARIA_DE_URUACU("SUBSEÇÃO JUDICIÁRIA DE URUAÇU", "URC", UnidadeFederativaEnum.GO, "3505"),
    SUBSECAO_JUDICIARIA_DE_FORMOSA("SUBSEÇÃO JUDICIÁRIA DE FORMOSA", "FRM", UnidadeFederativaEnum.GO, "3506"),
    SUBSECAO_JUDICIARIA_DE_JATAI("SUBSEÇÃO JUDICIÁRIA DE JATAÍ", "JTI", UnidadeFederativaEnum.GO, "3507"),
    NUCLEOS_DE_JUSTICA_4_0("NÚCLEOS DE JUSTIÇA 4.0", "NJ", UnidadeFederativaEnum.DF, "1"),
    SUBSECAO_JUDICIARIA_DE_PASSOS("SUBSEÇÃO JUDICIÁRIA DE PASSOS", "PSS", UnidadeFederativaEnum.MG, "3804"),
    SUBSECAO_JUDICIARIA_DE_SAO_SEBASTIAO_DO_PARAISO("SUBSEÇÃO JUDICIÁRIA DE SÃO SEBASTIÃO DO PARAÍSO", "SSP", UnidadeFederativaEnum.MG, "3805"),
    SUBSECAO_JUDICIARIA_DE_PATOS_DE_MINAS("SUBSEÇÃO JUDICIÁRIA DE PATOS DE MINAS", "PMS", UnidadeFederativaEnum.MG, "3806"),
    SUBSECAO_JUDICIARIA_DE_MONTES_CLAROS("SUBSEÇÃO JUDICIÁRIA DE MONTES CLAROS", "MCL", UnidadeFederativaEnum.MG, "3807"),
    SUBSECAO_JUDICIARIA_DE_LAVRAS("SUBSEÇÃO JUDICIÁRIA DE LAVRAS", "LAV", UnidadeFederativaEnum.MG, "3808"),
    SUBSECAO_JUDICIARIA_DE_VARGINHA("SUBSEÇÃO JUDICIÁRIA DE VARGINHA", "VGA", UnidadeFederativaEnum.MG, "3809"),
    SUBSECAO_JUDICIARIA_DE_POUSO_ALEGRE("SUBSEÇÃO JUDICIÁRIA DE POUSO ALEGRE", "PSA", UnidadeFederativaEnum.MG, "3810"),
    SUBSECAO_JUDICIARIA_DE_DIVINOPOLIS("SUBSEÇÃO JUDICIÁRIA DE DIVINÓPOLIS", "DVL", UnidadeFederativaEnum.MG, "3811"),
    SUBSECAO_JUDICIARIA_DE_SETE_LAGOAS("SUBSEÇÃO JUDICIÁRIA DE SETE LAGOAS", "SLA", UnidadeFederativaEnum.MG, "3812"),
    SUBSECAO_JUDICIARIA_DE_GOVERNADOR_VALADARES("SUBSEÇÃO JUDICIÁRIA DE GOVERNADOR VALADARES", "GVS", UnidadeFederativaEnum.MG, "3813"),
    SUBSECAO_JUDICIARIA_DE_IPATINGA("SUBSEÇÃO JUDICIÁRIA DE IPATINGA", "IIG", UnidadeFederativaEnum.MG, "3814"),
    SUBSECAO_JUDICIARIA_DE_SAO_JOAO_DEL_REI("SUBSEÇÃO JUDICIÁRIA DE SÃO JOÃO DEL REI", "SOE", UnidadeFederativaEnum.MG, "3815"),
    SUBSECAO_JUDICIARIA_DE_TEOFILO_OTONI("SUBSEÇÃO JUDICIÁRIA DE TEÓFILO OTONI", "TOT", UnidadeFederativaEnum.MG, "3816"),
    SUBSECAO_JUDICIARIA_DE_PARACATU("SUBSEÇÃO JUDICIÁRIA DE PARACATU", "PTU", UnidadeFederativaEnum.MG, "3817"),
    SUBSECAO_JUDICIARIA_DE_UNAI("SUBSEÇÃO JUDICIÁRIA DE UNAÍ", "UNI", UnidadeFederativaEnum.MG, "3818"),
    SUBSECAO_JUDICIARIA_DE_MANHUACU("SUBSEÇÃO JUDICIÁRIA DE MANHUAÇU", "MNC", UnidadeFederativaEnum.MG, "3819"),
    SUBSECAO_JUDICIARIA_DE_CONTAGEM("SUBSEÇÃO JUDICIÁRIA DE CONTAGEM", "CEM", UnidadeFederativaEnum.MG, "3820"),
    SUBSECAO_JUDICIARIA_DE_MURIAE("SUBSEÇÃO JUDICIÁRIA DE MURIAÉ", "MRE", UnidadeFederativaEnum.MG, "3821"),
    SUBSECAO_JUDICIARIA_DE_CAMPO_FORMOSO("SUBSEÇÃO JUDICIÁRIA DE CAMPO FORMOSO", "CFS", UnidadeFederativaEnum.BA, "3302"),
    SUBSECAO_JUDICIARIA_DE_BARREIRAS("SUBSEÇÃO JUDICIÁRIA DE BARREIRAS", "BES", UnidadeFederativaEnum.BA, "3303"),
    SUBSECAO_JUDICIARIA_DE_FEIRA_DE_SANTANA("SUBSEÇÃO JUDICIÁRIA DE FEIRA DE SANTANA", "FSA", UnidadeFederativaEnum.BA, "3304"),
    SUBSECAO_JUDICIARIA_DE_JUAZEIRO("SUBSEÇÃO JUDICIÁRIA DE JUAZEIRO", "JZR", UnidadeFederativaEnum.BA, "3305"),
    SUBSECAO_JUDICIARIA_DE_PAULO_AFONSO("SUBSEÇÃO JUDICIÁRIA DE PAULO AFONSO", "PAF", UnidadeFederativaEnum.BA, "3306"),
    SUBSECAO_JUDICIARIA_DE_VITORIA_DA_CONQUISTA("SUBSEÇÃO JUDICIÁRIA DE VITÓRIA DA CONQUISTA", "VCA", UnidadeFederativaEnum.BA, "3307"),
    SUBSECAO_JUDICIARIA_DE_JEQUIE("SUBSEÇÃO JUDICIÁRIA DE JEQUIÉ", "JEE", UnidadeFederativaEnum.BA, "3308"),
    SUBSECAO_JUDICIARIA_DE_GUANAMBI("SUBSEÇÃO JUDICIÁRIA DE GUANAMBI", "GNB", UnidadeFederativaEnum.BA, "3309"),
    SUBSECAO_JUDICIARIA_DE_EUNAPOLIS("SUBSEÇÃO JUDICIÁRIA DE EUNÁPOLIS", "EUS", UnidadeFederativaEnum.BA, "3310"),
    SUBSECAO_JUDICIARIA_DE_ITABUNA("SUBSEÇÃO JUDICIÁRIA DE ITABUNA", "ITB", UnidadeFederativaEnum.BA, "3311"),
    SUBSECAO_JUDICIARIA_DE_IRECE("SUBSEÇÃO JUDICIÁRIA DE IRECÊ", "IEE", UnidadeFederativaEnum.BA, "3312"),
    SUBSECAO_JUDICIARIA_DE_TEIXEIRA_DE_FREITAS("SUBSEÇÃO JUDICIÁRIA DE TEIXEIRA DE FREITAS", "TAF", UnidadeFederativaEnum.BA, "3313"),
    SUBSECAO_JUDICIARIA_DE_ALAGOINHAS("SUBSEÇÃO JUDICIÁRIA DE ALAGOINHAS", "ALH", UnidadeFederativaEnum.BA, "3314"),
    SUBSECAO_JUDICIARIA_DE_BOM_JESUS_DA_LAPA("SUBSEÇÃO JUDICIÁRIA DE BOM JESUS DA LAPA", "BMP", UnidadeFederativaEnum.BA, "3315"),
    SUBSECAO_JUDICIARIA_DE_PICOS("SUBSEÇÃO JUDICIÁRIA DE PICOS", "PCZ", UnidadeFederativaEnum.PI, "4001"),
    SUBSECAO_JUDICIARIA_DE_PARNAIBA("SUBSECAO JUDICIARIA DE PARNAIBA", "PNA", UnidadeFederativaEnum.PI, "4002"),
    SUBSECAO_JUDICIARIA_DE_FLORIANO("SUBSEÇÃO JUDICIÁRIA DE FLORIANO", "FLO", UnidadeFederativaEnum.PI, "4003"),
    SUBSECAO_JUDICIARIA_DE_SAO_RAIMUNDO_NONATO("SUBSEÇÃO JUDICIÁRIA DE SAO RAIMUNDO NONATO", "SRN", UnidadeFederativaEnum.PI, "4004"),
    SUBSECAO_JUDICIARIA_DE_CORRENTE("SUBSEÇÃO JUDICIÁRIA DE CORRENTE", "CNT", UnidadeFederativaEnum.PI, "4005"),
    SUBSECAO_JUDICIARIA_DE_ARAGUAINA("SUBSEÇÃO JUDICIÁRIA DE ARAGUAÍNA", "ARN", UnidadeFederativaEnum.TO, "4301"),
    SUBSECAO_JUDICIARIA_DE_GURUPI("SUBSEÇÃO JUDICIÁRIA DE GURUPI", "GUR", UnidadeFederativaEnum.TO, "4302"),
    SUBSECAO_JUDICIARIA_DE_ITUMBIARA("SUBSEÇÃO JUDICIÁRIA DE ITUMBIARA", "IUB", UnidadeFederativaEnum.GO, "3508"),
    SUBSECAO_JUDICIARIA_DE_ALTAMIRA("SUBSEÇÃO JUDICIÁRIA DE ALTAMIRA", "ATM", UnidadeFederativaEnum.PA, "3903"),
    SUBSECAO_JUDICIARIA_DE_CASTANHAL("SUBSEÇÃO JUDICIÁRIA DE CASTANHAL", "CAH", UnidadeFederativaEnum.PA, "3904"),
    SUBSECAO_JUDICIARIA_DE_REDENCAO("SUBSEÇÃO JUDICIÁRIA DE REDENCAO", "RDO", UnidadeFederativaEnum.PA, "3905"),
    SUBSECAO_JUDICIARIA_DE_PARAGOMINAS("SUBSEÇÃO JUDICIÁRIA DE PARAGOMINAS", "PGN", UnidadeFederativaEnum.PA, "3906"),
    SUBSECAO_JUDICIARIA_DE_TUCURUI("SUBSEÇÃO JUDICIÁRIA DE TUCURUÍ", "TUU", UnidadeFederativaEnum.PA, "3907"),
    SUBSECAO_JUDICIARIA_DE_ITAITUBA("SUBSEÇÃO JUDICIÁRIA DE ITAITUBA", "IAB", UnidadeFederativaEnum.PA, "3908"),
    SUBSECAO_JUDICIARIA_DE_CAXIAS("SUBSEÇÃO JUDICIÁRIA DE CAXIAS", "CXS", UnidadeFederativaEnum.MA, "3702"),
    SUBSECAO_JUDICIARIA_DE_BACABAL("SUBSEÇÃO JUDICIÁRIA DE BACABAL", "BBL", UnidadeFederativaEnum.MA, "3703"),
    SUBSECAO_JUDICIARIA_DE_BALSAS("SUBSEÇÃO JUDICIÁRIA DE BALSAS", "BLA", UnidadeFederativaEnum.MA, "3704"),
    SUBSECAO_JUDICIARIA_DE_LARANJAL_DO_JARI("SUBSEÇÃO JUDICIÁRIA DE LARANJAL DO JARI", "LJI", UnidadeFederativaEnum.AP, "3101"),
    SUBSECAO_JUDICIARIA_DE_OIAPOQUE("SUBSEÇÃO JUDICIÁRIA DE OIAPOQUE", "OPQ", UnidadeFederativaEnum.AP, "3102"),
    SUBSECAO_JUDICIARIA_DE_PONTE_NOVA("SUBSEÇÃO JUDICIÁRIA DE PONTE NOVA", "PNV", UnidadeFederativaEnum.MG, "3822"),
    SUBSECAO_JUDICIARIA_DE_VICOSA("SUBSEÇÃO JUDICIÁRIA DE VIÇOSA", "VCS", UnidadeFederativaEnum.MG, "3823"),
    SUBSECAO_JUDICIARIA_DE_ITUIUTABA("SUBSEÇÃO JUDICIÁRIA DE ITUIUTABA", "IUA", UnidadeFederativaEnum.MG, "3824"),
    SUBSECAO_JUDICIARIA_DE_JANAUBA("SUBSEÇÃO JUDICIÁRIA DE JANAÚBA", "JUA", UnidadeFederativaEnum.MG, "3825"),
    SUBSECAO_JUDICIARIA_DE_POCOS_DE_CALDAS("SUBSEÇÃO JUDICIÁRIA DE POÇOS DE CALDAS", "PCS", UnidadeFederativaEnum.MG, "3826"),
    SUBSECAO_JUDICIARIA_DE_UBERLANDIA("SUBSEÇÃO JUDICIÁRIA DE UBERLÂNDIA", "UDI", UnidadeFederativaEnum.MG, "3803"),
    SUBSECAO_JUDICIARIA_DE_UBERABA("SUBSEÇÃO JUDICIÁRIA DE UBERABA", "UBE", UnidadeFederativaEnum.MG, "3802"),
    SUBSECAO_JUDICIARIA_DE_JUIZ_DE_FORA("SUBSEÇÃO JUDICIÁRIA DE JUIZ DE FORA", "JFO", UnidadeFederativaEnum.MG, "3801"),
    SUBSECAO_JUDICIARIA_DE_JI_PARANA("SUBSEÇÃO JUDICIÁRIA DE JI-PARANÁ", "JIP", UnidadeFederativaEnum.RO, "4101"),
    SUBSECAO_JUDICIARIA_DE_GUAJARA_MIRIM("SUBSEÇÃO JUDICIÁRIA DE GUAJARÁ-MIRIM", "GUM", UnidadeFederativaEnum.RO, "4102"),
    SUBSECAO_JUDICIARIA_DE_JUINA("SUBSEÇÃO JUDICIÁRIA DE JUÍNA", "JNA", UnidadeFederativaEnum.MT, "3606"),
    SUBSECAO_JUDICIARIA_DE_CACERES("SUBSEÇÃO JUDICIÁRIA DE CÁCERES", "CCS", UnidadeFederativaEnum.MT, "3601"),
    SUBSECAO_JUDICIARIA_DE_RONDONOPOLIS("SUBSEÇÃO JUDICIÁRIA DE RONDONÓPOLIS", "ROI", UnidadeFederativaEnum.MT, "3602"),
    SUBSECAO_JUDICIARIA_DE_SINOP("SUBSEÇÃO JUDICIÁRIA DE SINOP", "SNO", UnidadeFederativaEnum.MT, "3603"),
    SUBSECAO_JUDICIARIA_DE_CRUZEIRO_DO_SUL("SUBSEÇÃO JUDICIÁRIA DE CRUZEIRO DO SUL", "CZU", UnidadeFederativaEnum.AC, "3001"),
    SUBSECAO_JUDICIARIA_DE_VILHENA("SUBSEÇÃO JUDICIÁRIA DE VILHENA", "VHA", UnidadeFederativaEnum.RO, "4103"),
    SUBSECAO_JUDICIARIA_DE_SANTAREM("SUBSEÇÃO JUDICIÁRIA DE SANTARÉM", "STM", UnidadeFederativaEnum.PA, "3902"),
    SUBSECAO_JUDICIARIA_DE_ILHEUS("SUBSEÇÃO JUDICIÁRIA DE ILHÉUS", "ILS", UnidadeFederativaEnum.BA, "3301"),
    SECAO_JUDICIARIA_DO_ESTADO_DE_MINAS_GERAIS("SEÇÃO JUDICIÁRIA DO ESTADO DE MINAS GERAIS", "JFMG", UnidadeFederativaEnum.MG, "3800"),
    SUBSECAO_JUDICIARIA_DE_IMPERATRIZ("SUBSEÇÃO JUDICIÁRIA DE IMPERATRIZ", "ITZ", UnidadeFederativaEnum.MA, "3701"),
    SUBSECAO_JUDICIARIA_DE_MARABA("SUBSEÇÃO JUDICIÁRIA DE MARABÁ", "MBA", UnidadeFederativaEnum.PA, "3901"),
    SECAO_JUDICIARIA_DO_ESTADO_DO_AMAZONAS("SEÇÃO JUDICIÁRIA DO ESTADO DO AMAZONAS", "JFAM", UnidadeFederativaEnum.AM, "3200"),
    SUBSECAO_JUDICIARIA_DE_TABATINGA("SUBSEÇÃO JUDICIÁRIA DE TABATINGA", "TBT", UnidadeFederativaEnum.AM, "3201"),
    SUBSECAO_JUDICIARIA_DE_TEFE("SUBSEÇÃO JUDICIÁRIA DE TEFÉ", "TFE", UnidadeFederativaEnum.AM, "3202"),
    SECAO_JUDICIARIA_DO_ESTADO_DO_PARA("SEÇÃO JUDICIÁRIA DO ESTADO DO PARÁ", "JFPA", UnidadeFederativaEnum.PA, "3900"),
    SECAO_JUDICIARIA_DO_ESTADO_DO_MARANHAO("SEÇÃO JUDICIÁRIA DO ESTADO DO MARANHÃO", "JFMA", UnidadeFederativaEnum.MA, "3700"),
    SECAO_JUDICIARIA_DO_ESTADO_DO_AMAPA("SEÇÃO JUDICIÁRIA DO ESTADO DO AMAPÁ", "JFAP", UnidadeFederativaEnum.AP, "3100"),
    SECAO_JUDICIARIA_DO_ESTADO_DO_ACRE("SEÇÃO JUDICIÁRIA DO ESTADO DO ACRE", "JFAC", UnidadeFederativaEnum.AC, "3000"),
    SECAO_JUDICIARIA_DO_ESTADO_DE_RONDÔNIA("SEÇÃO JUDICIÁRIA DO ESTADO DE RONDÔNIA", "JFRO", UnidadeFederativaEnum.RO, "4100"),
    SECAO_JUDICIARIA_DO_ESTADO_DE_MATO_GROSSO("SEÇÃO JUDICIÁRIA DO ESTADO DE MATO GROSSO", "JFMT", UnidadeFederativaEnum.MT, "3600"),
    SECAO_JUDICIARIA_DO_ESTADO_DE_RORAIMA("SEÇÃO JUDICIÁRIA DO ESTADO DE RORAIMA", "JFRR", UnidadeFederativaEnum.RR, "4200"),
    SECAO_JUDICIARIA_DO_ESTADO_DE_GOIAS("SEÇÃO JUDICIÁRIA DO ESTADO DE GOIÁS", "JFGO", UnidadeFederativaEnum.GO, "3500"),
    SECAO_JUDICIARIA_DO_ESTADO_DA_BAHIA("SEÇÃO JUDICIÁRIA DO ESTADO DA BAHIA", "JFBA", UnidadeFederativaEnum.BA, "3300"),
    SECAO_JUDICIARIA_DO_ESTADO_DO_PIAUI("SEÇÃO JUDICIÁRIA DO ESTADO DO PIAUÍ", "JFPI", UnidadeFederativaEnum.PI, "4000"),
    SECAO_JUDICIARIA_DO_ESTADO_DO_TOCANTINS("SEÇÃO JUDICIÁRIA DO ESTADO DO TOCANTINS", "JFTO", UnidadeFederativaEnum.TO, "4300"),
    SECAO_JUDICIARIA_DO_DISTRITO_FEDERAL("SEÇÃO JUDICIÁRIA DO DISTRITO FEDERAL", "JFDF", UnidadeFederativaEnum.DF, "3400"),
    SUBSECAO_JUDICIARIA_DE_DIAMANTINO("SUBSEÇÃO JUDICIÁRIA DE DIAMANTINO", "DIO", UnidadeFederativaEnum.MT, "3604"),
    SUBSECAO_JUDICIARIA_DE_BARRA_DO_GARCAS("SUBSEÇÃO JUDICIÁRIA DE BARRA DO GARÇAS", "BAG", UnidadeFederativaEnum.MT, "3605"),
    SUBSECAO_JUDICIARIA_DE_LUZIANIA("SUBSEÇÃO JUDICIÁRIA DE LUZIANIA", "LZA", UnidadeFederativaEnum.GO, "3501");

    private final String nome;
    private final String sigla;
    private final UnidadeFederativaEnum unidadeFederativa;
    private final String codigo;

    OrigensTRF1Enum(String nome, String sigla, UnidadeFederativaEnum unidadeFederativa, String codigo) {
        this.nome = nome;
        this.sigla = sigla;
        this.unidadeFederativa = unidadeFederativa;
        this.codigo = codigo;
    }

    public String getNome() {
        return nome;
    }

    public String getSigla() {
        return sigla;
    }

    public UnidadeFederativaEnum getUnidadeFederativa() {
        return unidadeFederativa;
    }

    public String getCodigo() {
        return codigo;
    }
}
